features:
  favicon: 1
logo:
  use_default: 0
  path: themes/custom/mtm_foundation/logo.png
favicon:
  use_default: 1
  path: ''
zurb_foundation_status_in_reveal: 0
zurb_foundation_use_respondjs: 0
zurb_foundation_meta_header_grid: 1
zurb_foundation_top_bar_enable: '2'
zurb_foundation_top_bar_grid: 0
zurb_foundation_top_bar_sticky: 1
zurb_foundation_top_bar_scrolltop: 1
zurb_foundation_top_bar_is_hover: 1
zurb_foundation_top_bar_menu_text: ''
zurb_foundation_top_bar_custom_back_text: 0
zurb_foundation_top_bar_back_text: ''
zurb_foundation_top_bar_mobile_show_parent_link: 0
zurb_foundation_top_bar_search: 0
zurb_foundation_page_site_name: 1
zurb_foundation_page_site_logo: 0
zurb_foundation_page_account_info: 1
zurb_foundation_disable_base_css: 0
zurb_foundation_disable_base_js: 0
